### PR TITLE
output number of files created

### PR DESCRIPTION
**Pull request by eddiemonge**
give the user an indication something was done

babel

### CODE REVIEW

**Comment by sindresorhus** [comment]
:-1: I'm lukewarm on this. The unix practise is to be silent on success and loud on failure. If you want to see what's happening there's always the `--verbose

**Comment by eddiemonge** [comment]
This just puts it more in line with the contrib plugins

**Comment by eddiemonge** [comment]
This just puts it more in line with the contrib plugins

**Comment by eddiemonge** [comment]
:(

**Comment by eddiemonge** [comment]
6 months later and I still think I'm right on this one:

babel

Without some kind of output, it looks like this task failed compared to the other grunt tasks. While the unix way is to be silent, the grunt way is to give some kind of confirmation

**Pull request closed without merging**
