### PR TITLE
Babel 7 has moved to @babel namespace

### PR DESCRIPTION
**Pull request by exsilium**
Hi! Opened this Pull request to get insight and get the discussion going on how to move forward with grunt-babel consuming and requiring @babel/core instead of babel-core. Thanks!

===
- Updating dependencies
- Require @babel/core instead of babel-core
- Updated lock

### CODE REVIEW

**Comment by oychao** [comment]
This is exactly what I'm looking for.

**Comment by kaynz** [comment]
I've tested this and it's working :)

@hzoo Could you merge this?

**Comment by danez** [comment]
Thanks this is merged in commit  005be65

**Comment by danez** [comment]
Support for scoped babel 7 packages was released in 8.0.0-beta.0

**Pull request closed without merging**
