### PR TITLE
upgrade babel-core to 6.17.0

### PR DESCRIPTION
**Pull request by mickaelvalmier**

### CODE REVIEW

**Comment by mickaelvalmier** [comment]
Hi,

Fix when class throw Reference Error like that : 
- https://github.com/babel/babel/issues/1560
- https://github.com/babel/babel/issues/689

Thanks.

**Comment by sindresorhus** [comment]
The semver specifier already matches that version. No change needed.

https://nodesource.com/blog/semver-tilde-and-caret

**Comment by mickaelvalmier** [comment]
Of course, i know semver specifier,  but explicit the minimum version needed by including some minor criticism is not a bad idea for outdated systems

**Comment by sindresorhus** [comment]
Set it in your own package.json then, and npm@3 will dedupe it to the Babel version you specified.

**Comment by mickaelvalmier** [comment]
Already defined (with npm@3.10.5), but npm wants nothing.
... but i have upgrade my presets used and its works.

Thanks for your replies !

Another question, your CI failed with node < 1.0.0 due to strict mode not specified on xo ... but when looking into project is set ?


Regards.

**Pull request closed without merging**
